# Generated by Django 4.2.2 on 2023-12-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='tagline',
            field=models.CharField(default='placeholdertagline', max_length=200),
            preserve_default=False,
        ),
    ]
