# Generated by Django 4.2.2 on 2023-12-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsstory_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(default='Uncategorised', max_length=200),
        ),
    ]
