# Generated by Django 4.2.2 on 2023-12-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='author',
        ),
    ]
